"""
Rejection sampling / thinning simulation for the homogeneous-region  model
with ERK negative feedback.

Workflow implemented here:
  1. Keep the rejection sampling / thinning structure.
  2. Use the same left-limit conventions as the consistent animation script:
       - active zone A(V^a_{s-}): S_i^a < s <= S_i^a + T_i^a,
       - ERK protected zone A(V^p_{s-}): S_j^d < s <= S_j^d + T_j^d.
  3. Burn-in first, by default 500 observed deaths.
  4. Then collect and analyze the next 200 observed deaths.
  5. Stop as soon as burn_in_deaths + target_deaths observed deaths are accepted.
  6. Save statistics on the analyzed observed death process:
       - number of analyzed observed deaths,
       - time needed for the analyzed 200 deaths after burn-in,
       - mean / median inter-death time after burn-in,
       - death-candidate rejection rates,
       - spatial coefficient of variation with a uniform reference,
       - Pearson chi-square uniformity test on a coarser grid.
  7. Plot a histogram in time after burn-in.
  8. Plot a 2D histogram in space with a common colorbar scale across scenarios.
  9. Play with several parameter sets and save a comparison CSV file.

"""

from __future__ import annotations

from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Any, Dict, List, Tuple
import csv
import json
import math
import zipfile

import matplotlib
matplotlib.use("Agg")  # non-interactive backend for batch simulations

import matplotlib.pyplot as plt
import numpy as np

try:
    from scipy.stats import chi2 as scipy_chi2
except Exception:  # pragma: no cover - fallback if scipy is unavailable
    scipy_chi2 = None
import textwrap

def pretty_scenario_name(name: str, width: int = 32) -> str:
    return textwrap.fill(name.replace("_", " "), width=width)
# ============================================================
# 1. Parameters
# ============================================================

OUTPUT_DIR = Path("simulation_outputs_homogeneous_200_rejection_consistent_burnin_optimized")


@dataclass(frozen=True)
class Params:
    name: str = "baseline"
    seed: int = 123

    # Spatial window W = [0, Lx] x [0, Ly]
    Lx: float = 10.0
    Ly: float = 10.0

    # Rejection-sampling simulation is generated by finite candidate blocks.
    # The true stopping time is the time of death number burn_in_deaths + target_deaths.
    block_duration: float = 10.0
    max_blocks: int = 2000

    # Burn-in and target.
    # Statistics are computed only for the target_deaths after burn-in.
    burn_in_deaths: int = 500
    target_deaths: int = 200

    # Activation process V^a_t.
    # lambda_a_1 is the dominating candidate intensity on W.
    # lambda_a_c is the background intensity outside active zones.
    lambda_a_1: float = 0.60
    lambda_a_c: float = 0.05

    # Activation marks: R^a ~ Exp(beta_a_R), T^a ~ Exp(beta_a_T).
    beta_a_R: float = 1.4
    beta_a_T: float = 0.8

    # Candidate death process Phi^d on W.
    lambda_d: float = 0.25

    # Protection marks after accepted deaths: R^d ~ Exp(beta_d_R), T^d ~ Exp(beta_d_T).
    beta_d_R: float = 1.2
    beta_d_T: float = 0.6

    # Plotting/statistics choices.
    # With only 200 analyzed deaths, 10 x 10 is useful for visualization and CV.
    # A coarser 5 x 5 grid gives expected count 200/25 = 8 for the chi-square test.
    time_bins: int = 20
    space_bins: int = 10
    chi2_bins: int = 5

    @property
    def area_W(self) -> float:
        return self.Lx * self.Ly

    @property
    def total_deaths_to_simulate(self) -> int:
        return self.burn_in_deaths + self.target_deaths


@dataclass
class SimulationResult:
    name: str
    params: Params

    # All accepted observed deaths, including burn-in.
    death_x_all: np.ndarray
    death_y_all: np.ndarray
    death_t_all: np.ndarray

    # Analyzed observed deaths, after burn-in.
    death_x: np.ndarray
    death_y: np.ndarray
    death_t: np.ndarray              # raw time values
    death_t_since_burnin: np.ndarray # time relative to burn-in end

    # Accepted activation centers, historical.
    activation_x: np.ndarray
    activation_y: np.ndarray
    activation_t: np.ndarray

    burn_in_time: float
    final_time: float
    analysis_time_span: float

    target_deaths: int
    burn_in_deaths_requested: int
    total_deaths_simulated: int
    observed_deaths_analyzed: int
    stopped_by_target: bool

    activation_candidates_processed: int
    activation_accepted: int
    activation_rejected: int

    death_candidates_processed: int
    death_rejected_outside_active: int
    death_rejected_by_erk: int
    erk_zones_created_total: int


# ============================================================
# 2. Geometry: active and protected zones
# ============================================================


def validate_params(p: Params) -> None:
    if not (0.0 <= p.lambda_a_c < p.lambda_a_1):
        raise ValueError("Need 0 <= lambda_a_c < lambda_a_1 for rejection sampling.")
    for key in ["beta_a_R", "beta_a_T", "lambda_d", "beta_d_R", "beta_d_T"]:
        if getattr(p, key) <= 0:
            raise ValueError(f"Need {key} > 0.")
    if p.Lx <= 0 or p.Ly <= 0:
        raise ValueError("Need positive domain size.")
    if p.block_duration <= 0 or p.max_blocks <= 0:
        raise ValueError("Need positive block_duration and max_blocks.")
    if p.burn_in_deaths < 0 or p.target_deaths <= 0:
        raise ValueError("Need burn_in_deaths >= 0 and target_deaths > 0.")
    if p.space_bins <= 0 or p.chi2_bins <= 0 or p.time_bins <= 0:
        raise ValueError("Need positive histogram bin numbers.")


def point_in_active_zone_lists(
    x: float,
    y: float,
    s: float,
    X_acc: List[float],
    Y_acc: List[float],
    S_acc: List[float],
    R_acc: List[float],
    Tau_acc: List[float],
) -> bool:
    """
    Return True if (x,y) belongs to A(V^a_{s-}).

    Consistent left-limit convention:
        S_i^a < s <= S_i^a + T_i^a.
    The strict inequality S_i^a < s prevents a candidate from accepting itself.
    """
    for xk, yk, sk, rk, tauk in zip(X_acc, Y_acc, S_acc, R_acc, Tau_acc):
        if sk < s <= sk + tauk:
            if (x - xk) ** 2 + (y - yk) ** 2 <= rk ** 2:
                return True
    return False


def point_in_protected_zone_lists(
    x: float,
    y: float,
    s: float,
    X_death: List[float],
    Y_death: List[float],
    S_death: List[float],
    R_death: List[float],
    Tau_death: List[float],
) -> bool:
    """
    Return True if (x,y) belongs to A(V^p_{s-}).

    Consistent left-limit convention:
        S_j^d < s <= S_j^d + T_j^d.
    """
    for xj, yj, sj, rj, tauj in zip(X_death, Y_death, S_death, R_death, Tau_death):
        if sj < s <= sj + tauj:
            if (x - xj) ** 2 + (y - yj) ** 2 <= rj ** 2:
                return True
    return False


# ============================================================
# 3. Rejection sampling / thinning simulation
# ============================================================


def simulate_one(p: Params) -> SimulationResult:
    """
    Simulate until burn_in_deaths + target_deaths observed deaths are accepted.

    Candidate activations are generated on each block, accepted
    recursively in chronological order, and candidate deaths are then tested
    against A(V^a_{s-}) and A(V^p_{s-}).
    """
    validate_params(p)
    rng = np.random.default_rng(p.seed)

    # Accepted activation centers V^a.
    X_acc: List[float] = []
    Y_acc: List[float] = []
    S_acc: List[float] = []
    R_acc: List[float] = []
    Tau_acc: List[float] = []

    # Accepted observed deaths V^d and their ERK marks V^p.
    X_death: List[float] = []
    Y_death: List[float] = []
    S_death: List[float] = []
    R_death: List[float] = []
    Tau_death: List[float] = []

    activation_candidates_processed = 0
    activation_rejected = 0
    death_candidates_processed = 0
    death_rejected_outside_active = 0
    death_rejected_by_erk = 0

    t0 = 0.0

    def point_in_active_zone_arrays(
        x: float,
        y: float,
        s: float,
        X_arr: np.ndarray,
        Y_arr: np.ndarray,
        S_arr: np.ndarray,
        R_arr: np.ndarray,
        Tau_arr: np.ndarray,
    ) -> bool:
        """Vectorized test for (x,y) in A(V^a_{s-})."""
        if len(X_arr) == 0:
            return False
        active_before_s = (S_arr < s) & (s <= S_arr + Tau_arr)
        if not np.any(active_before_s):
            return False
        dx = x - X_arr[active_before_s]
        dy = y - Y_arr[active_before_s]
        rr = R_arr[active_before_s]
        return bool(np.any(dx * dx + dy * dy <= rr * rr))

    for _block in range(p.max_blocks):
        t1 = t0 + p.block_duration

        # ----------------------------------------------------
        # A) Candidate activations in W x [t0,t1]
        # ----------------------------------------------------
        n_act = int(rng.poisson(p.lambda_a_1 * p.area_W * p.block_duration))
        activation_candidates_processed += n_act

        act_x = rng.uniform(0.0, p.Lx, size=n_act)
        act_y = rng.uniform(0.0, p.Ly, size=n_act)
        act_s = rng.uniform(t0, t1, size=n_act)
        act_u = rng.uniform(0.0, 1.0, size=n_act)
        act_r = rng.exponential(scale=1.0 / p.beta_a_R, size=n_act)
        act_tau = rng.exponential(scale=1.0 / p.beta_a_T, size=n_act)

        for idx in np.argsort(act_s):
            x = float(act_x[idx])
            y = float(act_y[idx])
            s = float(act_s[idx])
            u = float(act_u[idx])
            r = float(act_r[idx])
            tau = float(act_tau[idx])

            inside_active = point_in_active_zone_lists(x, y, s, X_acc, Y_acc, S_acc, R_acc, Tau_acc)

            # Rejection / thinning rule from the consistent script:
            # p^a_v(x) = 1 if x in A(v), lambda_a_c / lambda_a_1 otherwise.
            if inside_active or (u <= p.lambda_a_c / p.lambda_a_1):
                X_acc.append(x)
                Y_acc.append(y)
                S_acc.append(s)
                R_acc.append(r)
                Tau_acc.append(tau)
            else:
                activation_rejected += 1

        # Convert accepted activations once per block for fast death tests.
        X_acc_arr = np.asarray(X_acc)
        Y_acc_arr = np.asarray(Y_acc)
        S_acc_arr = np.asarray(S_acc)
        R_acc_arr = np.asarray(R_acc)
        Tau_acc_arr = np.asarray(Tau_acc)

        # ----------------------------------------------------
        # B) Candidate deaths in W x [t0,t1]
        # ----------------------------------------------------
        n_death_star = int(rng.poisson(p.lambda_d * p.area_W * p.block_duration))

        d_x = rng.uniform(0.0, p.Lx, size=n_death_star)
        d_y = rng.uniform(0.0, p.Ly, size=n_death_star)
        d_s = rng.uniform(t0, t1, size=n_death_star)
        d_r = rng.exponential(scale=1.0 / p.beta_d_R, size=n_death_star)
        d_tau = rng.exponential(scale=1.0 / p.beta_d_T, size=n_death_star)

        for idx in np.argsort(d_s):
            if len(S_death) >= p.total_deaths_to_simulate:
                break

            xd = float(d_x[idx])
            yd = float(d_y[idx])
            sd = float(d_s[idx])
            rd = float(d_r[idx])
            taud = float(d_tau[idx])

            death_candidates_processed += 1

            inside_active = point_in_active_zone_arrays(
                xd, yd, sd, X_acc_arr, Y_acc_arr, S_acc_arr, R_acc_arr, Tau_acc_arr
            )
            inside_protected = point_in_protected_zone_lists(
                xd, yd, sd, X_death, Y_death, S_death, R_death, Tau_death
            )

            # Observed death is accepted iff it is inside active zones and outside ERK protection.
            if inside_active and not inside_protected:
                X_death.append(xd)
                Y_death.append(yd)
                S_death.append(sd)
                R_death.append(rd)
                Tau_death.append(taud)
            else:
                if inside_protected:
                    death_rejected_by_erk += 1
                else:
                    death_rejected_outside_active += 1

        if len(S_death) >= p.total_deaths_to_simulate:
            break

        t0 = t1
    else:
        raise RuntimeError(
            f"Only {len(S_death)} observed deaths after {p.max_blocks} blocks. "
            "Increase block_duration, max_blocks, lambda_d, or activation parameters."
        )

    # Keep exactly burn-in + target deaths.
    X_all = np.asarray(X_death[:p.total_deaths_to_simulate])
    Y_all = np.asarray(Y_death[:p.total_deaths_to_simulate])
    S_all = np.asarray(S_death[:p.total_deaths_to_simulate])

    if len(S_all) > p.burn_in_deaths:
        burn_in_time = 0.0 if p.burn_in_deaths == 0 else float(S_all[p.burn_in_deaths - 1])
        X_an = X_all[p.burn_in_deaths:]
        Y_an = Y_all[p.burn_in_deaths:]
        S_an = S_all[p.burn_in_deaths:]
        S_since_burnin = S_an - burn_in_time
        analysis_time_span = float(S_all[-1] - burn_in_time) if len(S_an) else 0.0
    else:
        burn_in_time = float(S_all[-1]) if len(S_all) else 0.0
        X_an = np.array([])
        Y_an = np.array([])
        S_an = np.array([])
        S_since_burnin = np.array([])
        analysis_time_span = 0.0

    return SimulationResult(
        name=p.name,
        params=p,
        death_x_all=X_all,
        death_y_all=Y_all,
        death_t_all=S_all,
        death_x=X_an,
        death_y=Y_an,
        death_t=S_an,
        death_t_since_burnin=S_since_burnin,
        activation_x=np.asarray(X_acc),
        activation_y=np.asarray(Y_acc),
        activation_t=np.asarray(S_acc),
        burn_in_time=burn_in_time,
        final_time=float(S_all[-1]) if len(S_all) else 0.0,
        analysis_time_span=analysis_time_span,
        target_deaths=p.target_deaths,
        burn_in_deaths_requested=p.burn_in_deaths,
        total_deaths_simulated=len(S_all),
        observed_deaths_analyzed=len(S_an),
        stopped_by_target=(len(S_all) >= p.total_deaths_to_simulate),
        activation_candidates_processed=activation_candidates_processed,
        activation_accepted=len(X_acc),
        activation_rejected=activation_rejected,
        death_candidates_processed=death_candidates_processed,
        death_rejected_outside_active=death_rejected_outside_active,
        death_rejected_by_erk=death_rejected_by_erk,
        erk_zones_created_total=len(S_all),
    )


# ============================================================
# 4. Statistics
# ============================================================


def spatial_histogram(result: SimulationResult, bins: int) -> np.ndarray:
    p = result.params
    H, _, _ = np.histogram2d(
        result.death_x,
        result.death_y,
        bins=bins,
        range=[[0.0, p.Lx], [0.0, p.Ly]],
    )
    return H


def chi2_stats_from_histogram(H: np.ndarray) -> Tuple[float, int, float, float]:
    """Return chi2 statistic, df, chi2/df, and p-value if scipy is available."""
    n = float(np.sum(H))
    k = int(H.size)
    expected = n / k if k > 0 else np.nan
    if not np.isfinite(expected) or expected <= 0:
        return np.nan, k - 1, np.nan, np.nan
    chi2_uniform = float(np.sum((H - expected) ** 2 / expected))
    df = k - 1
    chi2_per_df = chi2_uniform / df if df > 0 else np.nan
    p_value = float(scipy_chi2.sf(chi2_uniform, df)) if scipy_chi2 is not None and df > 0 else np.nan
    return chi2_uniform, df, chi2_per_df, p_value


def death_statistics(result: SimulationResult) -> Dict[str, Any]:
    p = result.params

    if len(result.death_t) > 0:
        inter_death_after_burnin = np.diff(np.concatenate([[result.burn_in_time], result.death_t]))
    else:
        inter_death_after_burnin = np.array([])

    H_plot = spatial_histogram(result, p.space_bins)
    expected_plot = result.observed_deaths_analyzed / float(p.space_bins * p.space_bins)
    spatial_cv = float(np.std(H_plot) / np.mean(H_plot)) if np.mean(H_plot) > 0 else np.nan
    empty_bins = int(np.sum(H_plot == 0))

    k_plot = p.space_bins * p.space_bins
    expected_cv_uniform_plot = (
        float(np.sqrt((k_plot - 1) / result.observed_deaths_analyzed))
        if result.observed_deaths_analyzed > 0 else np.nan
    )
    spatial_cv_ratio_to_uniform = (
        spatial_cv / expected_cv_uniform_plot
        if np.isfinite(expected_cv_uniform_plot) and expected_cv_uniform_plot > 0 else np.nan
    )

    H_chi2 = spatial_histogram(result, p.chi2_bins)
    expected_chi2 = result.observed_deaths_analyzed / float(p.chi2_bins * p.chi2_bins)
    chi2_coarse, df_coarse, chi2_per_df_coarse, p_value_coarse = chi2_stats_from_histogram(H_chi2)

    total_death_rejected = result.death_rejected_outside_active + result.death_rejected_by_erk
    death_rejection_rate = (
        total_death_rejected / result.death_candidates_processed
        if result.death_candidates_processed > 0 else np.nan
    )
    death_rejection_rate_outside_active = (
        result.death_rejected_outside_active / result.death_candidates_processed
        if result.death_candidates_processed > 0 else np.nan
    )
    death_rejection_rate_by_erk = (
        result.death_rejected_by_erk / result.death_candidates_processed
        if result.death_candidates_processed > 0 else np.nan
    )
    death_acceptance_rate_total = (
        result.total_deaths_simulated / result.death_candidates_processed
        if result.death_candidates_processed > 0 else np.nan
    )

    return {
        "scenario": result.name,
        "seed": p.seed,
        "burn_in_deaths": p.burn_in_deaths,
        "analyzed_target_deaths": p.target_deaths,
        "total_deaths_simulated": result.total_deaths_simulated,
        "n_observed_deaths_analyzed": result.observed_deaths_analyzed,
        "stopped_by_target": result.stopped_by_target,
        "burn_in_time": result.burn_in_time,
        "raw_final_time": result.final_time,
        "total_time_for_analyzed_200_deaths_after_burnin": result.analysis_time_span,
        "observed_death_rate_after_burnin": result.observed_deaths_analyzed / result.analysis_time_span if result.analysis_time_span > 0 else np.nan,
        "mean_inter_death_time_after_burnin": float(np.mean(inter_death_after_burnin)) if len(inter_death_after_burnin) else np.nan,
        "median_inter_death_time_after_burnin": float(np.median(inter_death_after_burnin)) if len(inter_death_after_burnin) else np.nan,
        "activation_candidates_processed": result.activation_candidates_processed,
        "activation_accepted": result.activation_accepted,
        "activation_rejected": result.activation_rejected,
        "activation_rejection_rate": result.activation_rejected / result.activation_candidates_processed if result.activation_candidates_processed > 0 else np.nan,
        "death_candidates_processed": result.death_candidates_processed,
        "death_rejected_outside_active": result.death_rejected_outside_active,
        "death_rejected_by_erk": result.death_rejected_by_erk,
        "death_rejected_total": total_death_rejected,
        "death_rejection_rate": death_rejection_rate,
        "death_rejection_rate_outside_active": death_rejection_rate_outside_active,
        "death_rejection_rate_by_erk": death_rejection_rate_by_erk,
        "death_acceptance_rate_total": death_acceptance_rate_total,
        "erk_zones_created_total": result.erk_zones_created_total,
        "spatial_bins_per_axis_for_plot": p.space_bins,
        "spatial_expected_count_per_plot_bin_if_uniform": expected_plot,
        "spatial_coefficient_of_variation_plot_bins": spatial_cv,
        "spatial_expected_cv_if_uniform_plot_bins": expected_cv_uniform_plot,
        "spatial_cv_ratio_to_uniform_plot_bins": spatial_cv_ratio_to_uniform,
        "spatial_empty_bins_plot_bins": empty_bins,
        "spatial_bins_per_axis_for_chi2_test": p.chi2_bins,
        "spatial_expected_count_per_chi2_bin_if_uniform": expected_chi2,
        "spatial_chi2_statistic_against_uniform_counts_chi2_bins": chi2_coarse,
        "spatial_chi2_df_chi2_bins": df_coarse,
        "spatial_chi2_per_df_chi2_bins": chi2_per_df_coarse,
        "spatial_chi2_p_value_chi2_bins": p_value_coarse,
        "lambda_a_1": p.lambda_a_1,
        "lambda_a_c": p.lambda_a_c,
        "lambda_d": p.lambda_d,
        "beta_a_R": p.beta_a_R,
        "beta_a_T": p.beta_a_T,
        "beta_d_R": p.beta_d_R,
        "beta_d_T": p.beta_d_T,
    }


# ============================================================
# 5. Output helpers
# ============================================================


def save_death_events_csv(result: SimulationResult, out_dir: Path) -> Path:
    path = out_dir / f"{result.name}_observed_deaths_after_burnin.csv"
    p = result.params
    raw_indices = np.arange(p.burn_in_deaths + 1, p.burn_in_deaths + result.observed_deaths_analyzed + 1)
    analysis_indices = np.arange(1, result.observed_deaths_analyzed + 1)
    data = np.column_stack([
        analysis_indices,
        raw_indices,
        result.death_t,
        result.death_t_since_burnin,
        result.death_x,
        result.death_y,
    ])
    header = "analysis_death_index,raw_death_index,raw_death_time,time_since_burnin,x,y"
    np.savetxt(
        path,
        data,
        delimiter=",",
        header=header,
        comments="",
        fmt=["%d", "%d", "%.10f", "%.10f", "%.10f", "%.10f"],
    )
    return path


def plot_time_histogram(result: SimulationResult, out_dir: Path) -> Path:
    p = result.params
    path = out_dir / f"{result.name}_time_histogram_after_burnin.png"
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(result.death_t_since_burnin, bins=p.time_bins, range=(0.0, result.analysis_time_span))
    ax.set_xlabel("time after burn-in")
    ax.set_ylabel("number of observed deaths")
    ax.set_title(
        f"Observed cell death times after burn-in — {result.name}\n"
        f"burn-in = {p.burn_in_deaths}, N = {result.observed_deaths_analyzed}, "
        f"time span = {result.analysis_time_span:.3f}"
    )
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def plot_spatial_histogram_2d(result: SimulationResult, out_dir: Path, colorbar_vmax: int) -> Path:
    p = result.params
    path = out_dir / f"{result.name}_space_2d_histogram_after_burnin.png"
    H = spatial_histogram(result, p.space_bins)
    fig, ax = plt.subplots(figsize=(8, 6), constrained_layout=True)

    image = ax.imshow(
        H.T,
        origin="lower",
        extent=[0.0, p.Lx, 0.0, p.Ly],
        aspect="equal",
        interpolation="nearest",
        vmin=0,
        vmax=colorbar_vmax,
    )
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    scenario_label = pretty_scenario_name(result.name)

    ax.set_title(
    f"2D histogram of observed death locations\n"
    f"{scenario_label}\n"
    f"after burn-in {p.burn_in_deaths}, "
    f"{p.space_bins} x {p.space_bins} bins, N = {result.observed_deaths_analyzed}",
    fontsize=11,
    pad=12,
)
    cbar = fig.colorbar(image, ax=ax, label="number of observed deaths")
    cbar.set_ticks(np.arange(0, colorbar_vmax + 1, max(1, colorbar_vmax // 8)))
    
    fig.savefig(path, dpi=200, bbox_inches="tight", pad_inches=0.25)
    plt.close(fig)
    return path


def plot_death_locations(result: SimulationResult, out_dir: Path) -> Path:
    p = result.params
    path = out_dir / f"{result.name}_death_locations_after_burnin.png"
    fig, ax = plt.subplots(figsize=(8, 6), constrained_layout=True)
    ax.scatter(result.death_x, result.death_y, s=18)
    ax.set_xlim(0.0, p.Lx)
    ax.set_ylim(0.0, p.Ly)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    scenario_label = pretty_scenario_name(result.name)

    ax.set_title(
    f"Observed death locations after burn-in\n"
    f"N = {result.observed_deaths_analyzed}\n"
    f"{scenario_label}",
    fontsize=11,
    pad=12,
    )
    fig.savefig(path, dpi=200, bbox_inches="tight", pad_inches=0.25)
    plt.close(fig)
    return path


def plot_cumulative_deaths(result: SimulationResult, out_dir: Path) -> Path:
    path = out_dir / f"{result.name}_cumulative_deaths_after_burnin.png"
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.step(result.death_t_since_burnin, np.arange(1, result.observed_deaths_analyzed + 1), where="post")
    ax.set_xlabel("time after burn-in")
    ax.set_ylabel("cumulative observed deaths after burn-in")
    ax.set_title(f"Cumulative observed deaths after burn-in — {result.name}")
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def save_parameters_and_summary_json(result: SimulationResult, stats: Dict[str, Any], out_dir: Path) -> None:
    with (out_dir / f"{result.name}_parameters.json").open("w", encoding="utf-8") as f:
        json.dump(asdict(result.params), f, indent=2)
    with (out_dir / f"{result.name}_summary_after_burnin.json").open("w", encoding="utf-8") as f:
        json.dump(stats, f, indent=2)


def save_summary_csv(rows: List[Dict[str, Any]], out_dir: Path) -> Path:
    path = out_dir / "summary_homogeneous_200_after_burnin.csv"
    keys = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)
    return path


def plot_comparison_total_time(rows: List[Dict[str, Any]], out_dir: Path) -> Path:
    path = out_dir / "comparison_total_time_after_burnin_T200.png"
    names = [str(r["scenario"]) for r in rows]
    times = [float(r["total_time_for_analyzed_200_deaths_after_burnin"]) for r in rows]

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.bar(names, times)
    ax.set_ylabel("time for analyzed 200 observed deaths after burn-in")
    ax.set_title("Effect of parameters on stopping time after burn-in")
    ax.tick_params(axis="x", rotation=20)
    for label in ax.get_xticklabels():
        label.set_ha("right")
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def write_analysis_report(rows: List[Dict[str, Any]], out_dir: Path, colorbar_vmax: int) -> Path:
    path = out_dir / "spatial_uniformity_analysis_report_homogeneous_200.md"
    if not rows:
        path.write_text("No results.\n", encoding="utf-8")
        return path

    first = rows[0]
    n = int(first["n_observed_deaths_analyzed"])
    bins_plot = int(first["spatial_bins_per_axis_for_plot"])
    k_plot = bins_plot * bins_plot
    bins_chi2 = int(first["spatial_bins_per_axis_for_chi2_test"])
    k_chi2 = bins_chi2 * bins_chi2
    df_chi2 = k_chi2 - 1
    expected_plot = n / k_plot
    expected_chi2 = n / k_chi2
    cv_ref = math.sqrt((k_plot - 1) / n)
    sd_reduced = math.sqrt(2.0 / df_chi2)

    lines: List[str] = []
    lines.append("# Homogeneous-region observed death analysis after burn-in\n\n")
    lines.append(f"All 2D histograms use the same colorbar scale: 0 to {colorbar_vmax} observed deaths per bin.\n\n")
    lines.append(
        f"The simulation keeps the rejection sampling / thinning structure. "
        f"The first {int(first['burn_in_deaths'])} observed deaths are used as burn-in and are not used for statistics. "
        f"The reported statistics use the next {n} observed deaths.\n\n"
    )

    lines.append("## Mathematical/statistical interpretation\n\n")
    lines.append("### Spatial coefficient of variation\n\n")
    lines.append(
        "Let the spatial window be divided into equal-area bins and let `H_i` be the observed death count in bin `i`. "
        "The spatial coefficient of variation is\n\n"
    )  
    lines.append(
        "$$ CV_{\\mathrm{space}} = \\frac{\\mathrm{sd}(H_1,\\ldots,H_k)}{\\mathrm{mean}(H_1,\\ldots,H_k)} $$\n\n"
    )
    lines.append(
        "Under spatial uniformity, the bin counts are approximately multinomial with probability `1/k` per bin. "
        "Thus a useful finite-sample reference is\n\n"
    )
    lines.append(
        "$$\n"
        "CV_{\\mathrm{uniform}}\n"
        "\\approx\n"
        "\\sqrt{\\frac{k-1}{n}}.\n"
        "$$\n\n"
    )
    
    lines.append(
        f"For the {bins_plot} x {bins_plot} plot grid, `k = {k_plot}` and `n = {n}`, so "
        f"`CV_uniform ≈ sqrt(({k_plot}-1)/{n}) = {cv_ref:.3f}`. "
        "The ratio `CV_observed / CV_uniform` is therefore easier to interpret than the raw CV alone.\n\n"
    )

    lines.append("### Chi-square uniformity test\n\n")
    lines.append(
        f"The {bins_plot} x {bins_plot} grid is useful for visualization, but its expected count under uniformity is "
        f"`{n}/{k_plot} = {expected_plot:.2f}` per bin. "
        f"For the formal chi-square test, the script uses a coarser {bins_chi2} x {bins_chi2} grid, "
        f"where the expected count is `{n}/{k_chi2} = {expected_chi2:.2f}` per bin.\n\n"
    )
    lines.append("The Pearson statistic is\n\n")
    lines.append(
        "$$ X^2 = \\sum_{i=1}^{k} \\frac{(O_i-E_i)^2}{E_i} $$\n\n"
    )
    lines.append(
        f"Under spatial uniformity, `X^2` is approximately chi-square with `df = k-1 = {df_chi2}` degrees of freedom. "
        f"Therefore `X^2/df` should fluctuate around 1, with standard deviation approximately "
        f"`sqrt(2/df) = {sd_reduced:.3f}`. "
        "The p-value is the right-tail probability `P(chi2_df >= X_obs^2)`.\n\n"
    )

    lines.append("## Results\n\n")
    lines.append(
        "| scenario | time for analyzed 200 deaths | death rejection rate | outside-active rejection | ERK rejection | CV ratio to uniform | chi2/df | p-value | empty bins |\n"
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|\n"
    )
    for r in rows:
        lines.append(
            f"| {r['scenario']} | "
            f"{float(r['total_time_for_analyzed_200_deaths_after_burnin']):.3f} | "
            f"{float(r['death_rejection_rate']):.3f} | "
            f"{float(r['death_rejection_rate_outside_active']):.3f} | "
            f"{float(r['death_rejection_rate_by_erk']):.3f} | "
            f"{float(r['spatial_cv_ratio_to_uniform_plot_bins']):.3f} | "
            f"{float(r['spatial_chi2_per_df_chi2_bins']):.3f} | "
            f"{float(r['spatial_chi2_p_value_chi2_bins']):.3g} | "
            f"{int(r['spatial_empty_bins_plot_bins'])} |\n"
        )


    baseline = rows[0]
    fastest = min(rows, key=lambda r: float(r["total_time_for_analyzed_200_deaths_after_burnin"]))
    strongest_hetero = max(rows, key=lambda r: float(r["spatial_cv_ratio_to_uniform_plot_bins"]))
    lines.append("\n## Short conclusion\n\n")
    lines.append(
        f"The baseline analyzes exactly {int(baseline['n_observed_deaths_analyzed'])} deaths after burn-in. "
        f"Its CV ratio is {float(baseline['spatial_cv_ratio_to_uniform_plot_bins']):.3f}; "
        "values close to 1 are compatible with uniform multinomial fluctuations on the plotting grid.\n\n"
    )
    lines.append(
        f"The fastest scenario is `{fastest['scenario']}`, with "
        f"{float(fastest['total_time_for_analyzed_200_deaths_after_burnin']):.3f} time units for the analyzed 200 deaths.\n\n"
    )
    lines.append(
        f"The largest spatial CV ratio is obtained by `{strongest_hetero['scenario']}`, "
        f"with CV ratio {float(strongest_hetero['spatial_cv_ratio_to_uniform_plot_bins']):.3f}.\n"
    )

    path.write_text("".join(lines), encoding="utf-8")
    return path


def make_zip(out_dir: Path) -> Path:
    zip_path = out_dir.with_suffix(".zip")
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for file in out_dir.rglob("*"):
            if file.is_file():
                zf.write(file, arcname=file.relative_to(out_dir.parent))
    return zip_path


# ============================================================
# 6. Parameter sweep
# ============================================================


def make_scenarios(base: Params) -> Dict[str, Params]:
    """
    Parameter changes around the homogeneous baseline, keeping the same
    rejection sampling / thinning structure.

    Goal:
      - reduce death rejection rate,
      - keep the same biological acceptance rule:
            death accepted iff inside active zone and outside ERK protection,
      - compare parameter effects after burn-in.
    """
    return {
        "baseline": base,

        # More death candidates: mostly changes speed, not necessarily rejection rate.
        "higher_death_intensity": replace(
            base,
            name="higher_death_intensity",
            seed=124,
            lambda_d=0.35,
        ),

        # Increase active-zone coverage:
        # beta_a_R smaller -> larger active radius on average.
        # beta_a_T smaller -> longer active lifetime on average.
        # lambda_a_1 larger -> more activation candidates.
        "more_active_coverage": replace(
            base,
            name="more_active_coverage",
            seed=125,
            lambda_a_1=1.00,
            beta_a_R=1.00,
            beta_a_T=0.60,
        ),

        # Weaker ERK protection:
        # beta_d_R larger -> smaller ERK radius on average.
        # beta_d_T larger -> shorter ERK duration on average.
        "weaker_ERK": replace(
            base,
            name="weaker_ERK",
            seed=126,
            beta_d_R=2.50,
            beta_d_T=1.50,
        ),

        # Balanced optimization:
        # active zones are slightly larger/longer,
        # ERK protection is weaker,
        # but parameters are not too extreme.
        "balanced_optimized": replace(
            base,
            name="balanced_optimized",
            seed=127,
            lambda_a_1=1.00,
            beta_a_R=1.00,
            beta_a_T=0.60,
            beta_d_R=2.50,
            beta_d_T=1.50,
        ),

        # Stronger optimization test:
        # use this only if death rejection is still too high.
        "low_rejection_test": replace(
            base,
            name="low_rejection_test",
            seed=128,
            lambda_a_1=1.20,
            lambda_a_c=0.08,
            beta_a_R=0.90,
            beta_a_T=0.50,
            beta_d_R=3.00,
            beta_d_T=2.00,
        ),
    }


# ============================================================
# 7. Main
# ============================================================


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    base = Params(name="baseline", burn_in_deaths=500, target_deaths=200)
    scenarios = make_scenarios(base)

    print("Running homogeneous-region rejection sampling: burn-in 500 deaths, then analyze 200 deaths...\n")

    results: List[SimulationResult] = []
    for name, params in scenarios.items():
        print(f"Scenario: {name}")
        result = simulate_one(params)
        results.append(result)
        print(f"  total observed deaths simulated: {result.total_deaths_simulated}")
        print(f"  analyzed observed deaths:        {result.observed_deaths_analyzed}")
        print(f"  burn-in time:                    {result.burn_in_time:.6f}")
        print(f"  time for analyzed 200 deaths:    {result.analysis_time_span:.6f}")
        print("")

    # Common colorbar scale across all scenarios.
    global_colorbar_max = int(max(np.max(spatial_histogram(result, result.params.space_bins)) for result in results))
    global_colorbar_max = max(global_colorbar_max, 1)

    summary_rows: List[Dict[str, Any]] = []
    for result in results:
        stats = death_statistics(result)
        summary_rows.append(stats)

        save_death_events_csv(result, OUTPUT_DIR)
        save_parameters_and_summary_json(result, stats, OUTPUT_DIR)
        plot_time_histogram(result, OUTPUT_DIR)
        plot_spatial_histogram_2d(result, OUTPUT_DIR, global_colorbar_max)
        plot_death_locations(result, OUTPUT_DIR)
        plot_cumulative_deaths(result, OUTPUT_DIR)

        print(f"Scenario: {result.name}")
        print(f"  death rejection rate:   {stats['death_rejection_rate']:.4f}")
        print(f"    outside active:       {stats['death_rejection_rate_outside_active']:.4f}")
        print(f"    by ERK protection:    {stats['death_rejection_rate_by_erk']:.4f}")
        print(f"  spatial CV ratio:       {stats['spatial_cv_ratio_to_uniform_plot_bins']:.4f}")
        print(f"  chi2/df {result.params.chi2_bins}x{result.params.chi2_bins}:      {stats['spatial_chi2_per_df_chi2_bins']:.4f}")
        print(f"  chi2 p-value:           {stats['spatial_chi2_p_value_chi2_bins']:.4g}")
        print("")

    summary_path = save_summary_csv(summary_rows, OUTPUT_DIR)
    report_path = write_analysis_report(summary_rows, OUTPUT_DIR, global_colorbar_max)
    comparison_path = plot_comparison_total_time(summary_rows, OUTPUT_DIR)
    zip_path = make_zip(OUTPUT_DIR)

    print("Done.")
    print(f"Common colorbar vmax: {global_colorbar_max}")
    print(f"Summary CSV: {summary_path}")
    print(f"Analysis report: {report_path}")
    print(f"Comparison plot: {comparison_path}")
    print(f"Zip file: {zip_path}")
    print(f"All outputs are in: {OUTPUT_DIR.resolve()}")


if __name__ == "__main__":
    main()
