import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.patches import Circle


# ============================================================
# Offline construction of V_t with positive feedback
#
# No Gillespie event-driven simulation.
#
# Positive feedback intensity:
#   lambda_nu(y) = lambda_c + (lambda_1 - lambda_c) 1_{y in A(nu)}
#
# Active zone:
#   A(nu) = W cap union_i B(Y_i, R_i)
#
# Construction:
#   1. Simulate a dominant marked PPP with intensity lambda_1.
#   2. Sort candidate points by time.
#   3. Accept candidates by thinning:
#        - inside active zone: keep with probability 1
#        - outside active zone: keep with probability lambda_c / lambda_1
#   4. Accepted points become active centers.
#   5. At each time t:
#        V_t = sum_{k:S_k <= t < S_k + tau_k} delta_(Y_k, R_k)
# ============================================================


# -----------------------------
# 1. Parameters
# -----------------------------

seed = 123
rng = np.random.default_rng(seed)

# Spatial domain W = [0, Lx] x [0, Ly]
Lx = 10.0
Ly = 10.0
area_W = Lx * Ly

# Time horizon [0, T]
T = 20.0

# Background intensity outside active zones
lambda_c = 0.05

# Higher intensity inside active zones
lambda_1 = 0.80

if lambda_1 <= lambda_c:
    raise ValueError("We need lambda_1 > lambda_c.")

# Marks:
# R_k ~ Exp(beta_R)
# tau_k ~ Exp(beta_tau)
beta_R = 1.3
beta_tau = 0.8

# Animation parameters
n_frames = 300
interval_ms = 50

# Show only V_t, not all historical accepted events
show_history = False


# -----------------------------
# 2. Simulate dominant marked PPP
# -----------------------------

# Dominant PPP intensity is lambda_1 on W x [0,T]
# M ~ Poisson(lambda_1 * |W| * T)
mean_candidates = lambda_1 * area_W * T
M = rng.poisson(mean_candidates)

print(f"Nombre de points candidats simulés : M = {M}")

# Candidate positions X_j in W
X_cand = rng.uniform(0.0, Lx, size=M)
Y_cand = rng.uniform(0.0, Ly, size=M)

# Candidate birth times S_j in [0,T]
S_cand = rng.uniform(0.0, T, size=M)

# Uniform variables for thinning
U_cand = rng.uniform(0.0, 1.0, size=M)

# Candidate marks
R_cand = rng.exponential(scale=1.0 / beta_R, size=M)
tau_cand = rng.exponential(scale=1.0 / beta_tau, size=M)

# Sort candidates by time
order = np.argsort(S_cand)

X_cand = X_cand[order]
Y_cand = Y_cand[order]
S_cand = S_cand[order]
U_cand = U_cand[order]
R_cand = R_cand[order]
tau_cand = tau_cand[order]


# -----------------------------
# 3. Offline thinning with positive feedback
# -----------------------------

accepted_X = []
accepted_Y = []
accepted_S = []
accepted_R = []
accepted_tau = []

accepted_inside_flags = []


def is_inside_active_zone_at_time(x, y, s):
    """
    Check whether candidate point (x,y) is inside the active zone A(V_{s-}).

    A(V_{s-}) is built from previously accepted centers that are active just
    before time s.
    """
    for xk, yk, sk, rk, tauk in zip(
        accepted_X, accepted_Y, accepted_S, accepted_R, accepted_tau
    ):
        # active just before s:
        # sk <= s < sk + tauk is enough in simulation because ties have prob 0
        if sk <= s < sk + tauk:
            if (x - xk) ** 2 + (y - yk) ** 2 <= rk ** 2:
                return True
    return False


for x, y, s, u, r, tau in zip(
    X_cand, Y_cand, S_cand, U_cand, R_cand, tau_cand
):
    # Determine whether candidate is inside active zone generated by
    # previously accepted active centers.
    inside = is_inside_active_zone_at_time(x, y, s)

    if inside:
        # In active zone, target intensity = lambda_1.
        # Candidate intensity = lambda_1.
        # Accept with probability 1.
        accept = True
    else:
        # Outside active zone, target intensity = lambda_c.
        # Candidate intensity = lambda_1.
        # Accept with probability lambda_c / lambda_1.
        accept = u <= (lambda_c / lambda_1)

    if accept:
        accepted_X.append(x)
        accepted_Y.append(y)
        accepted_S.append(s)
        accepted_R.append(r)
        accepted_tau.append(tau)
        accepted_inside_flags.append(inside)


# Convert to NumPy arrays
X = np.array(accepted_X)
Y = np.array(accepted_Y)
S = np.array(accepted_S)
R = np.array(accepted_R)
tau = np.array(accepted_tau)
accepted_inside_flags = np.array(accepted_inside_flags, dtype=bool)

death_time = S + tau

print(f"Nombre de centres acceptés : N = {len(X)}")
print(f"Acceptés dans zone active : {np.sum(accepted_inside_flags)}")
print(f"Acceptés hors zone active : {len(X) - np.sum(accepted_inside_flags)}")


# -----------------------------
# 4. Functions to construct V_t
# -----------------------------

def active_mask(t):
    """
    Active centers at time t:

        S_k <= t < S_k + tau_k
    """
    return (S <= t) & (t < death_time)


def appeared_mask(t):
    """
    Centers already accepted before time t.
    """
    return S <= t


# -----------------------------
# 5. Create figure
# -----------------------------

fig, ax = plt.subplots(figsize=(7, 7))

ax.set_xlim(0, Lx)
ax.set_ylim(0, Ly)
ax.set_aspect("equal", adjustable="box")

ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_title("Offline simulation of $V_t$ with positive feedback")

# Optional history: accepted centers that are no longer active
history_scatter = ax.scatter(
    [],
    [],
    s=12,
    alpha=0.20,
    label="centres acceptés non actifs"
)

# Current active centers V_t
active_scatter = ax.scatter(
    [],
    [],
    s=50,
    label="centres actifs $V_t$"
)

time_text = ax.text(
    0.02,
    0.98,
    "",
    transform=ax.transAxes,
    va="top",
    ha="left"
)

count_text = ax.text(
    0.02,
    0.93,
    "",
    transform=ax.transAxes,
    va="top",
    ha="left"
)

info_text = ax.text(
    0.02,
    0.88,
    "",
    transform=ax.transAxes,
    va="top",
    ha="left"
)

ax.legend(loc="upper right")

active_circles = []


# -----------------------------
# 6. Animation functions
# -----------------------------

def init():
    history_scatter.set_offsets(np.empty((0, 2)))
    active_scatter.set_offsets(np.empty((0, 2)))
    time_text.set_text("")
    count_text.set_text("")
    info_text.set_text("")
    return history_scatter, active_scatter, time_text, count_text, info_text


def update(frame):
    global active_circles

    # Current time
    t = frame * T / (n_frames - 1)

    # Remove old active zone circles
    for c in active_circles:
        c.remove()
    active_circles = []

    is_active = active_mask(t)
    has_appeared = appeared_mask(t)

    inactive_appeared = has_appeared & (~is_active)

    if show_history:
        history_points = np.column_stack([X[inactive_appeared], Y[inactive_appeared]])
        history_scatter.set_offsets(history_points)
    else:
        history_scatter.set_offsets(np.empty((0, 2)))

    # Current V_t
    active_points = np.column_stack([X[is_active], Y[is_active]])
    active_scatter.set_offsets(active_points)

    # Draw active zones A(V_t)
    for xk, yk, rk in zip(X[is_active], Y[is_active], R[is_active]):
        circle = Circle(
            (xk, yk),
            rk,
            fill=False,
            alpha=0.45,
            linewidth=1.4
        )
        ax.add_patch(circle)
        active_circles.append(circle)

    n_active = int(np.sum(is_active))
    n_appeared = int(np.sum(has_appeared))

    time_text.set_text(f"t = {t:.2f}")
    count_text.set_text(f"Nombre de centres actifs = {n_active}")
    info_text.set_text(
        f"Centres acceptés avant t = {n_appeared} | "
        f"N total accepté = {len(X)}"
    )

    return history_scatter, active_scatter, time_text, count_text, info_text, *active_circles


# -----------------------------
# 7. Animation
# -----------------------------

anim = FuncAnimation(
    fig,
    update,
    frames=n_frames,
    init_func=init,
    interval=interval_ms,
    blit=False
)

plt.show()